spring.application.name=pagination-example

spring.datasource.url=jdbc:mysql://localhost:3306/practice
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Bhanu@898

# Show SQL queries in the console
spring.jpa.show-sql=true

# Automatically update schema based on entities (for development only)
spring.jpa.hibernate.ddl-auto=update

# Add this line to help Hibernate determine the correct dialect
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

server.port=8082
logging.level.org.springframework.web=DEBUG




